site_name: ""

nav:
  - Smart Import for Excel:
    - Getting Started:
      - Overview of Smart Excel Import: SmartImport/overview.md
      - Installation from AppSource: SmartImport/installation.md
      - Licensing & Free Trial: SmartImport/licensing.md
      - Permissions in BC: SmartImport/permissions.md

    - Core Concepts:
      - What is AI-Powered Import?: SmartImport/ai-powered-import.md
      - How Smart Import Works: SmartImport/how-it-works.md
      - Column Mapping: SmartImport/column-mapping.md
      - How Copilot Uses Excel: SmartImport/copilot-usage.md

    - Supported Import Destinations:
      - Journals: SmartImport/journals.md
      - Master Data: SmartImport/master-data.md

    - FAQ: SmartImport/faq.md
    

theme:
  name: material
  features:
    - navigation.path
    - navigation.tracking
    - navigation.accordion
  custom_dir: overrides
  favicon: assets/images/favicon.png
  search:
    lang: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - glightbox
  
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - assets/css/extra.css
