site_name: Evoleaps Help

nav:
  - Home: index.md
  - Smart Import:
    - Introduction: SmartImport/index.md
    - Getting Started: SmartImport/getting-started.md
    - Regenerate: SmartImport/regenerate.md
    - Error Handling: SmartImport/error-handling.md

theme:
  name: material  # Optional theme