site_name: ""

nav:

  - Smart Import:
    - Introduction: SmartImport/index.md
    - Getting Started: SmartImport/getting-started.md
    - Regenerate: SmartImport/regenerate.md
    - Error Handling: SmartImport/error-handling.md

theme:
  name: material  # Optional theme
  custom_dir: overrides
  #logo: assets/images/logo/smallGray.png  # Path to your logo
  favicon: assets/images/favicon.png
  search:
    lang: en  # Set the language of your documentation (e.g., 'en' for English)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode  
plugins:
  - search
  - glightbox
  
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - assets/css/extra.css
