site_name: Evoleaps Help

nav:
  - Home: index.md
  - SmartImport:
      - Overview: SmartImport/index.md
      - Setup: SmartImport/setup.md
      - Usage: SmartImport/usage.md
  - SmartWorkFlow:
      - Overview: SmartWorkFlow/index.md

theme:
  name: material  # Optional theme
